#!/usr/local/bin/node
const fs = require("fs");
const childProcess = require("child_process");

childProcess.exec("./node_modules/.bin/elm-analyse", (e, out) => {
  let file;
  let all = {};
  for (let line of out.split("\n")) {
    if (line.startsWith("-")) {
      file = line.slice(2);
      continue;
    }
    const matched = line.match(
      /.*Unused import `.*at.*\(\((\d+),(\d+)\),\((\d+),(\d+)\)\)/
    );
    if (matched) {
      if (!all[file]) {
        all[file] = [];
      }
      const [start, end] = [+matched[1], +matched[3]];
      all[file].push({ start, end });
    }
  }
  for (let file in all) {
    const contentArray = fs.readFileSync(file, "utf8").split("\n");
    const ranges = all[file];
    ranges.forEach(({ start, end }) => {
      for (let i = start - 1; i < end; i++) {
        contentArray[i] = null;
      }
    });
    const content = contentArray.filter(s => s !== null).join("\n");
    fs.writeFileSync(file, content);
  }
});
