#!/bin/bash
printf "\n\e[0;32m🍣   Starting elm-live...\e[0m\n\n"
node_modules/.bin/elm-live src/WidgetLogin/Main.elm src/WidgetIdLite/Main.elm src/WidgetTac/Main.elm src/WidgetRegistration/Main.elm --before-build=cmd/build/add_commit --open=true --dir=docs --port=8001 --path-to-elm=node_modules/.bin/elm -- --output=docs/js-compiled/widget-combined.js --debug
